### ISSUE TITLE
Saisie de nom

### ISSUE THREAD

**Issue by AAAurore** [AAAurore/Mus#2]
Problème rencontré :
Au moment du saisie de nom, si l'utilisateur saisit plus d’un mot, le système ne prend que le premier mot.

Solution imaginée :
Avertissement pour saisir un seul nom.
Deuxième tentative de saisie de nom.

**Comment by AAAurore** [comment]
Problème rencontré :
Au moment d’aller mus, si l’utilisateur répond par un mot ou par un chiffre supérieur à 4, le système s’arrête.

Solution imaginée :
Avertissement pour saisir un chiffre entre 1 et 4 et contient au maximum 4 chiffres, séparés de 3 virgules maximum.
Deuxième tentative de saisie de réponse choisie.

**Comment by AAAurore** [comment]
Suite à un bug, le commit et le push n'ont pas été effectué la semaine dernière. A refaire

**Comment by plevelu** [comment]
ok je prends

**Comment by plevelu** [comment]
C'est fait, j'ai changé la méhode de scanner, la nouvelle est scanner.nextLine() et plus scanner.next()
J'ai également ajouté un test au cas ou l'utilisatuer veuille rentrer une chaine vide, il ne pourra pas
