### ISSUE TITLE
Répondre à l'interface

### ISSUE THREAD

**Issue by AAAurore** [AAAurore/Mus#3]
Problème rencontré :
Au moment d’aller mus, si l’utilisateur répond par un mot ou par un chiffre supérieur à 4, le système s’arrête.

Solution imaginée :
Avertissement pour saisir un chiffre entre 1 et 4 et contient au maximum 4 chiffres, séparés de 3 virgules maximum.
Deuxième tentative de saisie de réponse choisie.

**Comment by AAAurore** [comment]
J'essaie ça

**Comment by arnaudfleury** [comment]
Je m'en charge.
