### ISSUE TITLE
Répondre avec choix multiples

### ISSUE THREAD

**Issue by AAAurore** [AAAurore/Mus#4]
Problème rencontré :
A chaque fois qu’il y a un choix de réponses possibles, il n’y a pas de gestion de cas d’erreur si l’utilisateur répond avec un ou plusieurs autres mots que les réponses attendues.

Solution imaginée :
Avertissement pour saisir une des réponses proposées.
Deuxième tentative de saisie de réponse choisie.

**Comment by arnaudfleury** [comment]
Je m'en charge.
