### ISSUE TITLE
Rappel du jeu

### ISSUE THREAD

**Issue by AAAurore** [AAAurore/Mus#5]
Problème rencontré :
Il n’y a pas de rappel du jeu, l’utilisateur doit remonter le terminal afin de voir son jeu.

Solution imaginée :
Ajout d'un dialogue pour ce rappel du jeu.

**Comment by plevelu** [comment]
je regarde...

**Comment by plevelu** [comment]
il existe une méthode afficherMain() dans le fichier AffichageConsoleEvenementDeJeu.java qui est privé, je vais l'appeler dans la méthode nouvellePhase() avec un petit texte indicatif par println juste avant.
Cela est fonctionnel, je ferme cette Issue
